AllCops:
  Excludes:
    - db/schema.rb
    - db/migrate/**/*
    - test/**/*

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
    Enabled: false